### ISSUE TITLE
Example_project Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by vbn22** [stephenmcd/django-socketio#73] opened 2014-10-24 09:26 UTC
Example_project:
<pre>
/usr/bin/python2.7 /home/vbn22/Desktop/django-socketio-master/django_socketio/example_project/manage.py runserver 8000
Performing system checks...

System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.

System check identified 1 issue (0 silenced).
October 24, 2014 - 03:36:23
Django version 1.7, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Oct/2014 03:37:40] "GET / HTTP/1.1" 200 856
[24/Oct/2014 03:37:41] "GET /favicon.ico HTTP/1.1" 404 1619
[24/Oct/2014 03:37:44] "GET /1 HTTP/1.1" 200 2620
[24/Oct/2014 03:37:44] "GET /static/js/chat.js HTTP/1.1" 200 3140
[24/Oct/2014 04:14:27] "GET / HTTP/1.1" 200 856
[24/Oct/2014 04:14:29] "GET /1 HTTP/1.1" 200 2620
</pre>

SocketIOServer:
<pre>
bash -cl "/usr/bin/python2.7 /home/vbn22/Desktop/pycharm/pycharm-3.4.1/helpers/pycharm/django_manage.py runserver_socketio /home/vbn22/Desktop/django-socketio-master/django_socketio/example_project"
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.

SocketIOServer running on 127.0.0.1:9000

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 495, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 490, in process_result
    self.socket.sendall('0\r\n\r\n')
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 458, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 435, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
{u'CSRF_COOKIE': u'7iD7Gr4hy9rzFUy3EeJQQmywpslp4SgL',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive, Upgrade',
 'HTTP_COOKIE': 'csrftoken=7iD7Gr4hy9rzFUy3EeJQQmywpslp4SgL; _xsrf=2|a8fbad65|32e6299edfce315a66210a5478baf6f7|1413918096; chatdemo_user="2|1:0|10:1413981652|13:chatdemo_user|388:eyJjbGFpbWVkX2lkIjogImh0dHBzOi8vd3d3Lmdvb2dsZS5jb20vYWNjb3VudHMvbzgvaWQ/aWQ9QUl0T2F3bmVPTmJVUGk1UGVEVlBzN05JbnlfM3VpNnNOb0FhTDl3IiwgImZpcnN0X25hbWUiOiAiXHUwNDNjXHUwNDM4XHUwNDQ1XHUwNDMwXHUwNDM4XHUwNDNiIiwgImxhc3RfbmFtZSI6ICJcdTA0MTJcdTA0MzBcdTA0M2RcdTA0MzVcdTA0MzVcdTA0MzIiLCAibmFtZSI6ICJcdTA0M2NcdTA0MzhcdTA0NDVcdTA0MzBcdTA0MzhcdTA0M2IgXHUwNDEyXHUwNDMwXHUwNDNkXHUwNDM1XHUwNDM1XHUwNDMyIn0=|298660cfb2b3ff8163b8bc7c068f3b1d2f4f3230d421e9301ee28c164f2b67a5"',
 'HTTP_HOST': '127.0.0.1:9000',
 'HTTP_ORIGIN': 'http://127.0.0.1:8000',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_SEC_WEBSOCKET_KEY': 'fnWStaxijJKEkNldP8nDdA==',
 'HTTP_SEC_WEBSOCKET_VERSION': '13',
 'HTTP_UPGRADE': 'websocket',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:33.0) Gecko/20100101 Firefox/33.0',
 'PATH_INFO': u'/socket.io/websocket',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '47735',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '9000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0xb74d10d0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0xb5c7be8c>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with error
</pre>

Firefox(Ubuntu):
<pre>
GET http://127.0.0.1:9000/socket.io/websocket [HTTP/1.1 500 INTERNAL SERVER ERROR]

Firefox can't establish a connection to the server at ws://127.0.0.1:9000/socket.io/websocket. socket.io.js:395

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:9000/socket.io/xhr-polling//1414142074796. This can be fixed by moving the resource to the same domain or enabling CORS.
</pre>
What am I doing wrong ?

**Comment by alexandervlpl** [comment] 2015-09-01 14:30
Duplicate of #39.

**Closed** 2016-08-30 05:57 UTC
