### ISSUE TITLE
Incorrect documentation for runserver_socketio

### ISSUE THREAD

**Issue by chrisspen** [stephenmcd/django-socketio#95] opened 2016-02-27 22:21 UTC
The docs specify:

"The runserver_socketio management command is provided which will run gevent’s pywsgi server which is required for supporting the type of long-running request a WebSocket will use:"

    $ python manage.py runserver_socketio host:port

However, running `manage.py runserver_socketio --help` shows the command does not accept any host:port argument, and that these values appear to be hard-coded to 127.0.0.1 and 9000.

**Comment by stephenmcd** [comment] 2016-02-27 22:46
Duplicate of #85

**Closed by stephenmcd** 2016-02-27 22:46 UTC

**Comment by chrisspen** [comment] 2016-02-27 22:59
How is this a duplicate of that closed ticket? The documentation is still wrong...

**Comment by stephenmcd** [comment] 2016-02-27 23:05
It's not closed

**Comment by xhafid** [comment] 2017-09-15 01:19
FAILED to start flash policy server: [Errno 13] Permission denied: ('0.0.0.0', 843)
