### ISSUE TITLE
handle_one_response() got an unexpected keyword argument 'call_wsgi_app'

### ISSUE THREAD

**Issue by chrisspen** [stephenmcd/django-socketio#96] opened 2016-02-27 22:33 UTC
Trying to enter a room in the chat example fails with the traceback:

    Traceback (most recent call last):
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/gevent/greenlet.py", line 390, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/socketio/server.py", line 49, in handle
        handler.handle()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 180, in handle
        result = self.handle_one_request()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 314, in handle_one_request
        self.handle_one_response()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/socketio/handler.py", line 58, in handle_one_response
        self.handle_one_response(call_wsgi_app=False)
    TypeError: handle_one_response() got an unexpected keyword argument 'call_wsgi_app'

This error occurs with Django>=1.7. It works if I downgrade to Django 1.6.

**Comment by stephenmcd** [comment] 2016-02-27 22:44
Duplicate of #79

**Closed by stephenmcd** 2016-02-27 22:44 UTC
